name: Simple CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: [self-hosted]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Environment
      run: |
        apt-get update && apt-get install -y python3 python3-pip wget unzip
        ln -sf /usr/bin/python3 /usr/bin/python
        ln -sf /usr/bin/pip3 /usr/bin/pip
        
        # Remove all existing Java versions
        apt-get remove -y --purge openjdk-* || true
        apt-get autoremove -y || true
        
        # Install Java 21 (SonarQube server ile aynı)
        apt-get install -y openjdk-21-jdk
        
        # Set Java 21
        export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
        echo "JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64" >> $GITHUB_ENV
        echo "/usr/lib/jvm/java-21-openjdk-amd64/bin" >> $GITHUB_PATH
        
        # Verify Java
        java -version
        which java
    
    - name: Unit Tests & Coverage
      run: |
        cd codebase
        pip install -r requirements.txt pytest pytest-cov
        python -m pytest tests/ \
          --cov=app \
          --cov-report=xml \
          --cov-fail-under=50 \
          -v
    
    - name: SonarQube Static Code Analysis
      run: |
        cd codebase
        
        # Ensure Java 21 (SonarQube server ile aynı)
        export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
        export PATH=/usr/lib/jvm/java-21-openjdk-amd64/bin:$PATH
        
        echo "Java verification:"
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
        
        # SonarQube'da token oluştur
        echo "Creating SonarQube token..."
        TOKEN=$(curl -u admin:admin -X POST \
          "http://sonarqube:9000/api/user_tokens/generate" \
          -d "name=pipeline-token-$(date +%s)" | \
          python3 -c "import sys, json; print(json.load(sys.stdin)['token'])" 2>/dev/null || echo "")
        
        if [ -z "$TOKEN" ]; then
          echo "Failed to create token, trying existing token..."
          TOKEN="admin"
        fi
        
        echo "Using token: ${TOKEN:0:10}..."
        
        # Download latest SonarQube Scanner (Java 21 uyumlu)
        wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
        unzip -q sonar-scanner-cli-6.2.1.4610-linux-x64.zip
        
        # Run SonarQube analysis with Java 21
        JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 \
        ./sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner \
          -Dsonar.projectKey=auth-service \
          -Dsonar.projectName="Authentication Service" \
          -Dsonar.sources=. \
          -Dsonar.exclusions="tests/**,**/__pycache__/**" \
          -Dsonar.host.url=http://sonarqube:9000 \
          -Dsonar.token="$TOKEN" \
          -Dsonar.python.coverage.reportPaths=coverage.xml
        
        echo "✅ SonarQube analysis completed!"
    
    - name: Build Docker Image
      run: |
        cd codebase
        docker build -t auth-service:latest .
    
    - name: Container Security Scan
      run: |
        trivy image \
          --server http://trivy-server:4954 \
          --severity CRITICAL \
          --exit-code 1 \
          auth-service:latest
    
    - name: Load Test
      run: |
        curl -X POST http://locust-master:8089/swarm \
          -d "user_count=10&spawn_rate=2&host=http://auth-service:5000" || true
        sleep 30
        curl -X GET http://locust-master:8089/stop || true
    
    - name: Push to ECR
      run: |
        cd codebase
        
        # ECR Login
        aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 708778582346.dkr.ecr.us-east-1.amazonaws.com
        
        # Tag and Push
        docker tag auth-service:latest 708778582346.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest
        docker push 708778582346.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest
        
        echo "✅ Pushed to ECR: 708778582346.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest"
